# This workflow will build a .NET Core project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: KIC Web Application CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]

    
env:
    AZURE_WEBAPP_NAME: keepitclean
    AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./KicWeb.sln
      
    - name: Build solution
      run: dotnet build ./KicWeb.sln --configuration Release --no-restore
      
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish ./KicWeb.sln --configuration Release --no-build --output '${{env.AZURE_WEBAPP_PACKAGE_PATH}}'
      
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
        package: "${{env.AZURE_WEBAPP_PACKAGE_PATH}}"
